### PR TITLE
feat: export all types from client with S3 prefix

### PR DESCRIPTION
**Pull request by karfau**
to make it possible to refer to the type of the constructor arguments from the outside without any "hacks".

### CODE REVIEW

**Comment by karfau** [comment]
I'm assuming the failing check is unrelated to my changes?

**Comment by bradenmacdonald** [comment]
Yeah, looks unrelated. I'll take a look when I can.
Thanks for this contribution, btw. I'll merge it as soon as I find time to resolve the failing check, merge your PR, and publish a new version.

**Comment by karfau** [comment]
In the meantime I was also thinking about exporting more types, especially the return types like `S3Object`. would you be fine if I add them as part of this PR?

**Comment by bradenmacdonald** [comment]
Sure, go for it!

**Pull request merged**
